### ISSUE TITLE
Vertical label layout breaks when used with inline help

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#2134]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

When You switch to vertical label layout as you can see it on this picture

<img width="1349" alt="Screen Shot 2020-03-05 at 9 13 36 PM" src="https://user-images.githubusercontent.com/17149942/76021876-581e5400-5f26-11ea-9074-ceda3031eacd.png">

The class:

```css
.fd-form-label--inline-help {
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
```
takes over and streatches label part  to 100% and shrings the actual control

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest `0.15.0-rc.17`

#### If this is a bug, please provide steps for reproducing it.
Please see above screenshot

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/core/input
#### Is there anything else we should know?

Also see #2133 and other related issues
