### ISSUE TITLE
Missing border line in popover component (dropdown)

### ISSUE THREAD

**Issue by biiit** [SAP/fundamental-ngx#774]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
show border-line above the arrow (right side)

If the following CSS is taken, the border is shown:
```css
working
.fd-dropdown__control::after {
    margin-top: -2px;
}

not working
.fd-dropdown__control::after {
    margin-top: -3px;
}
```

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7.2
fundamental-ngx 0.4.5
fiori-fundamentals 1.5.7

#### Please provide relevant source code if applicable.
```javascript
<div>
  <p>{{'CSM_Profile.Dialog.Companies' | translate}}</p>
  <fd-popover [isDropdown]="true">
    {{account.selectedCompany}}
    <fd-popover-body>
      <fd-menu>
        <ul fd-menu-list>
          <li fd-menu-item *ngFor="let company of account.companies" (click)="changeCompany(company)">
            {{company.name}}
          </li>
        </ul>
      </fd-menu>
    </fd-popover-body>
  </fd-popover>
</div>
```

#### Screenshot
![Screen Shot 2019-05-03 at 10 01 57](https://user-images.githubusercontent.com/12843264/57125748-c9332f00-6d8a-11e9-86ce-509ca08d6de8.png)
